<style>
#sideBareMenuGaucheurgence{ visibility: hidden }

#sideBareMenuGaucheurgence{ min-width:200px; max-width: 430px;}
</style>

<script>
$(window).load(function () {

	$('#waitMenuGaucheurgence').toggle(false);
	$('#sideBareMenuGaucheurgence').fadeIn().css({'visibility':'visible'});
	 
});
</script>

<div id="waitMenuGaucheurgence" style="color: #cccccc; font-size: 13px;  margin-top: 80px;  margin-left: 60px;" > <span> Chargement ... </span> </div>


<ul id="sideBareMenuGaucheurgence">
	<!-- MENU ***DOSSIER PATIENT*** -->
	<li id="dossier_patient"><a href="">
	    <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Dossier patient </span></a> 
	</li>

	<li id="plus_dossier_patient" style="background: #4a5765;" >

	   <div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/urgence/ajout-patient";?>"  >
	       <span id="nouveau_style" style="margin-left:5px; color: white; font-size:13px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>' alt='Liste' /> Nouveau</span></a>
	   </div>

	   <div style="margin-left:30px; height:40px;"><a href="<?php echo $this->basePath()."/urgence/liste-patient";?>">
	       <img style="margin-left:5px; display: inline; width: 18px; height: 18px; margin-top: -5px;" src='<?php echo $this->basePath().'/images_icons/list2.png'?>' />
	       <span id="liste_dossier_patient_style" style="font-size:13px; color: white; font-family:Times New Roman;">Liste</span></a>
	   </div>
	</li>



	<!-- MENU ***ADMISSION*** -->
	<li id="admission"><a href="">
	   <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/plus-green1.png'?>' alt='Liste' /> Urgence </span></a> 
	</li>

	<li id="plus_admission" style="background: #4a5765;" >

	   <div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath()."/urgence/admission";?>"  >
	      <span id="admission_style" style="margin-left:5px; color: white; font-size:13px; font-family:Times New Roman;"><img style="display: inline; width: 18px; height: 18px; margin-top: -5px;" src='<?php echo $this->basePath().'/images_icons/list2.png'?>' alt='Liste' /> Dossiers patients</span></a>
	   </div>

	   <div style="margin-left:30px; height:40px;"><a href="<?php echo $this->basePath()."/urgence/liste-patients-admis";?>">
	      <img style="margin-left:5px; display: inline; width: 18px; height: 18px; margin-top: -5px;" src='<?php echo $this->basePath().'/images_icons/list2.png'?>' alt='Liste' />
	      <span id="liste_admission_style" style="font-size:13px; color: white; font-family:Times New Roman;">Patients du service</span></a>
	   </div>
	   
	</li>
	
	<!-- MENU *** AFFICHAGE - TABLEAU STATISTIQUE *** infirmerie -->
	<li>
	   <div style="margin-left: 15px; border: 0.5px dashed gray; width: 80%; margin-top: 25px;"> </div>
	   <img onclick="affichagePatientsActesExamens();" style="margin-left: 15px; margin-top: 5px; margin-bottom: 5px; display: inline; cursor: pointer;" title="Actes et examens des patients" src='<?php echo $this->basePath().'/images_icons/infos.png'?>' />
	   <img onclick="imprimerRegistreDesPatientsAdmis();" style="margin-left: 10px; margin-top: 5px; margin-bottom: 5px; display: inline; cursor: pointer;" title="R&eacute;gistre &agrave; imprimer" src='<?php echo $this->basePath().'/images_icons/button_pdf.png'?>' />
	   	   
	</li>

</ul>


<?php
//CHOISIR LE MENU A AFFICHER SELON QUE C'EST LE MEDECIN OU LE SURVEILLANT
$user = $this->layout()->user;
$role = $user['role'];

if($role == 'urgence'){ ?>
<script>
$("#naissance").toggle(false);
$("#deces").toggle(false);
</script>
<?php
}
else if($role == 'etat_civil'){ ?>
<script>
//$("#dossier_patient").toggle(false);
$("#admission").toggle(false);
</script>
<?php
     }
?>


<script>
//*******************************************************************************************************************************
//NAISSANCE
function dep1(){
	$('#naissance').click(function(){
		$("#naissance").replaceWith("<li id='naissance'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/plus-green1.png' alt='Liste' /> Naissances </span></a></li>");
		dep2();
	    $('#plus_naissance').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep2(){
	$('#naissance').click(function(){
		$("#naissance").replaceWith("<li id='naissance' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Naissances </span></a></li>");
		dep1();
	    $('#plus_naissance').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_naissance').toggle(false);
$('#naissance').click(function(){
	$("#naissance").replaceWith("<li id='naissance' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Naissances </span></a></li>");
	dep1();
    $('#plus_naissance').animate({
        height : 'toggle'
    },1000);
 return false;
});

//*******************************************************************************************************************************
//DECES
function dep_deces1(){
	$('#deces').click(function(){
		$("#deces").replaceWith("<li id='deces'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/plus-green1.png' alt='Liste' /> D&eacute;c&egrave;s </span></a></li>");
		dep_deces2();
	    $('#plus_deces').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_deces2(){
	$('#deces').click(function(){
		$("#deces").replaceWith("<li id='deces' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> D&eacute;c&egrave;s </span></a></li>");
		dep_deces1();
	    $('#plus_deces').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_deces').toggle(false);
$('#deces').click(function(){
	$("#deces").replaceWith("<li id='deces' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> D&eacute;c&egrave;s </span></a></li>");
	dep_deces1();
    $('#plus_deces').animate({
        height : 'toggle'
    },1000);
 return false;
});


//*******************************************************************************************************************************
//ADMISSION
function dep_admission1(){
	$('#admission').click(function(){
		$("#admission").replaceWith("<li id='admission'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/plus-green1.png' alt='Liste' /> Urgence </span></a></li>");
		dep_admission2();
	    $('#plus_admission').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_admission2(){
	$('#admission').click(function(){
		$("#admission").replaceWith("<li id='admission' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Urgence </span></a></li>");
		dep_admission1();
	    $('#plus_admission').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_admission').toggle(false);
$('#admission').click(function(){
	$("#admission").replaceWith("<li id='admission' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Urgence </span></a></li>");
	dep_admission1();
$('#plus_admission').animate({
    height : 'toggle'
},1000);
return false;
});


//*******************************************************************************************************************************
//DOSSIER PATIENT
function dep_dossier_patient1(){
	$('#dossier_patient').click(function(){
		$("#dossier_patient").replaceWith("<li id='dossier_patient'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/plus-green1.png' alt='Liste' /> Dossier patient </span></a></li>");
		dep_dossier_patient2();
	    $('#plus_dossier_patient').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_dossier_patient2(){
	$('#dossier_patient').click(function(){
		$("#dossier_patient").replaceWith("<li id='dossier_patient' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Dossier patient </span></a></li>");
		dep_dossier_patient1();
	    $('#plus_dossier_patient').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_dossier_patient').toggle(false);
$('#dossier_patient').click(function(){
	$("#dossier_patient").replaceWith("<li id='dossier_patient' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='../images_icons/moin-green2.png' alt='Liste' /> Dossier patient </span></a></li>");
	dep_dossier_patient1();
$('#plus_dossier_patient').animate({
height : 'toggle'
},1000);
return false;
});

</script>




































<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/urgence/affichagePatientsActesExamens.css');?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/urgence/affichagePatientsActesExamens.js'); ?>

<!-- GESTION DE L'INTERFACE D'AFFICHAGE DES PATIENTS AYANT DES ACTES ET EXAMENS COMPLEMENTAIRES -->
<!-- GESTION DE L'INTERFACE D'AFFICHAGE DES PATIENTS AYANT DES ACTES ET EXAMENS COMPLEMENTAIRES -->
<!-- GESTION DE L'INTERFACE D'AFFICHAGE DES PATIENTS AYANT DES ACTES ET EXAMENS COMPLEMENTAIRES -->

<div id="affichagePatientsActesExamensMenuGauche" title="Actes et examens compl&eacute;mentaires des patients" style="display: none;" >

  <div id="contenuListePatientTableau">
  <div style='margin-right: 40px; float:right; font-family: Times New Roman; font-size: 15px; color: green;'> 
	<i style='cursor:pointer;' id='afficherPatientAujourdhui'> Aujourd'hui </i> | 
	<i style='cursor:pointer;' id='afficherPatientHier'> Hier </i> |
	<i style='cursor:pointer;' id='afficherPatientAvantHier'> Avant hier </i> | 
	<i style='cursor:pointer;' id='afficherPatientAutresJour'> Autres .. </i>
  </div>  
  
  <table style="width: 100%;  align: center" class="table table-bordered tab_list_mini" id="actesExamensComplementairesPatients">
	<thead>
		<tr>
			<th id="numeroDossierMG_" style='width: 30px;'>
			  <input type="text" name="search_browser" value=" N&deg; dossier" class="search_init_mg" />
			</th>
			<th id="nomMG_" style='width: 15%;'>
			  <input type="text"  name="search_browser" value=" Nom" class="search_init_mg" />
			</th>
			<th id="prenomMG_" style='width: 22%;'>
			  <input type="text" name="search_browser" value=" Pr&eacute;nom" class="search_init_mg" />
			</th>
			<th id="ageMG_" style='width: 5%;'>
			  <input type="text" name="search_browser" value=" Age" class="search_init_mg" />
			</th>
			<th id="adresseMG_" style='width: 43%;'>
			  <input type="text"  name="search_browser" value=" Adresse" class="search_init_mg" />
			</th>
			<th id="optionsMG_" style='width: 5%;'>
			  <input type="hidden" class="optionsAffichage"/>Options
			</th>
		</tr>

	</thead>

	<tbody id="donnees" class="liste_patient" style="font-family: times new roman; font-size: 19px;">

            <?php /* AFFICHAGE DE LA LISTE DES PATIENTS */?>

	</tbody>

  </table>
  
  </div>
  
  <div id="contenuInfoPatientActesExamen" style="display: none;">
  
    <div style="width: 100%; height: 30px;"><span style="float: left; font-size: 25px; cursor: pointer;" onclick="retourVersListePatientsActesExamens();" title="Pr&eacute;c&eacute;dent"> &#129092; </span></div>
    <div style="width: 100%;" id="contenuInfoPatientActesExamensComplementaire" >
  
    </div>
  </div>
  
</div>

<script>
   initialisationActesExamensComplementaires();
</script>












<!-- GESTION DE L'INTERFACE DE GENERATION DE REGISTRES -->
<!-- GESTION DE L'INTERFACE DE GENERATION DE REGISTRES -->
<!-- GESTION DE L'INTERFACE DE GENERATION DE REGISTRES -->

<div id="generationDesRegistresDesPatientsAdmisMenuGauche" title="G&eacute;n&eacute;rer la liste des patients admis (R&eacute;gistre)" style="display: none;" >


  <div class="optionsPeriodeMG" align="center">
    <div class="optionsPeriodePathMG" align="center">
           <div class="champOP1MG"><img onclick='imprimerRegistreDesPatientsAdmisParPeriode();' src='../images_icons/Apps-Pdf-B-icon-2.png' title='imprimer'><input type="date"></div> 
           <div class="champOP2MG"><input type="date"><button onclick="getRegistreDesPatientsAdmisPourPeriode();">Afficher</button></div>
    </div>    
  </div>

  
  <div class="zoneGenerationDesRegistresDesPatientsAdmis">
  
  
    <table style="width: 100%;" class="table table-bordered tab_list_mini" id="listePatientsAdmisPourLeRegistre">
	  
	  <thead style="width: 100%;">
		
		<tr style="width: 100%;">
		
			<th id="numeroDossierRegMG_" style='width: 10px;'>
			  <input type="text" name="search_browser" value=" N&deg; dossier" class="search_init_reg_mg" />
			</th>
			<th id="nomRegMG_" style='width: 10%;'>
			  <input type="text" name="search_browser" value=" Nom" class="search_init_reg_mg" />
			</th>
			<th id="prenomRegMG_" style='width: 20%;'>
			  <input type="text"  name="search_browser" value=" Pr&eacute;nom" class="search_init_reg_mg" />
			</th>
			<th id="ageRegMG_" style='width: 50px;'>
			  <input type="text"  name="search_browser" value=" Age" class="search_init_reg_mg" />
			</th>
			<th id="actesRegMG_" style='width: 20%;'>
			  <input type="text"  name="search_browser" value=" Actes" class="search_init_reg_mg" />
			</th>
			<th id="examensRegMG_" style='width: 20%;'>
			  <input type="text" name="search_browser" value=" Examens" class="search_init_reg_mg" />
			</th>
			<th id="diagnosticsRegMG_" style='width: 110px;'>
			  <input type="text" name="search_browser" value=" Diagnostics" class="search_init_reg_mg" />
			</th>
			
		</tr>

	  </thead>

	  <tbody id="donnees" class="liste_patient" style="font-family: times new roman; font-size: 19px;">

            <?php /* AFFICHAGE DE LA LISTE DES PATIENTS */?>

	  </tbody>

    </table>
  
  
  </div>

</div>


<div  style="display: none;">
<form id="imprimerRegistreDesPatientsAdmisPdf"> <button></button> </form>
</div>


<script>
  initialisationListePatientsAdmisRegistre();
</script>
