<html>
<?php echo $this->doctype("XHTML1_TRANSITIONAL"), PHP_EOL; ?>

<meta charset="UTF-8" />
        <?php echo $this->headTitle('SIMENS '. $this->translate('Systeme Information Medical'))->setSeparator(' - ')->setAutoEscape(false) ?>

<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<?php

 echo $this->headLink()->prependStylesheet($this->basePath().'/css/bootstrap.min.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/css/jquery.contextMenu.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/css/matrix-style-cons.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/css/matrix-media.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/js/w2ui/w2ui-1.4.3.min.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/css/menu-sidenav.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/css/editor-menugauche.scss');


 echo $this->headLink()->prependStylesheet($this->basePath().'/font-awesome/css/font-awesome.css');

 $this->headScript()->appendFile($this->basePath().'/js/jquery.min.js');
 $this->headScript()->appendFile($this->basePath().'/js/matrix.js');

 echo $this->headTitle($this->pageTitle);?> 
        <?php 
             echo $this->headLink()->appendStylesheet($this->basePath().'/css/smoothness/jquery-ui.css');
             echo $this->headLink()->appendStylesheet($this->basePath().'/js/plugins/multiselect/css/multi-select.css');
        ?>

        <?php $this->headScript()->appendFile($this->basePath().'/js/jquery-1.9.1.js');
		      $this->headScript()->appendFile($this->basePath().'/js/jquery-ui.js');
		      $this->headScript()->appendFile($this->basePath().'/js/jquery.dataTables.min.js');
		      $this->headScript()->appendFile($this->basePath().'/js/plugins/contextMenu/bootstrap-contextmenu.js');
		      
		      $this->headScript()->appendFile($this->basePath().'/js/jquery.maskedinput.js');
		      $this->headScript()->appendFile($this->basePath().'/js/controle_saisie/controle_saisie.js');

		      $this->headScript()->appendFile($this->basePath().'/js/plugins/multiselect/js/jquery.multi-select.js');
		      $this->headScript()->appendFile($this->basePath().'/js/plugins/multiselect/js/jquery.quicksearch.js');
		      
		      $this->headScript()->appendFile($this->basePath().'/js/w2ui/w2ui-1.4.3.min.js');

          //$this->headScript()->appendFile($this->basePath().'/js/bootstrap.min.js');
		?>

		<?php echo $this->headScript();?>
<head>
</head>


<?php

//RECUPERER LES INFOS SUR LE MEDECIN OU SUR LE SURVEILLANT
  $user = $this->layout()->user;
  $nom = $user['Nom'];
  $prenom = $user['Prenom'];
  $service = $this->layout()->service;
  if($user['role'] == 'superAdmin') { $service = "INFORMATIQUE";}
  
  $sexe = $user['Sexe'];
  $civilite =  'Mme';
  if($sexe == 'Masculin'){$civilite = 'M';}
  
  //var_dump($user['Photo']); exit();
?>


<body id="corps-page">


  <table style="width: 100%; height: 100%; background: white;">

      <tr style="width: 100%;">
        <!-- MENU GAUCHE -->
        <td id="menu-geuche-page" style="width: 16%; background: gree;">
          <!-- ENTETE -->
          <div style="position: fixed; top:0px; background: re; width:100%; height: 10%; ">
            <div id="logo-simens-style">
            SIMENS<sup>+</sup></div>
          </div>

          <!-- CORPS -->
          <div style="position: relative;  width:100%; height: 70%;  background: yello;">

              <ul class="accordion-menu" style="display:none;">
                <li>
                  <div class="dropdownlink">
                    <i class="icon-folder-close"></i> 
                      Dossier patient
                    <i class="icon-chevron-down" aria-hidden="true"></i>
                  </div>

                  <ul class="submenuItems">
                    <li><a class="nouveau-patient-select" href="<?php echo $this->basePath()."/urgence/ajout-patient";?>">Nouveau</a></li>
                    <li><a class="liste-patient-select" href="<?php echo $this->basePath()."/urgence/liste-patient";?>">Liste</a></li>
                  </ul>
                </li>

                <li>
                  <div class="dropdownlink">
                    <i class="icon-home" aria-hidden="true"></i> 
                      Urgences
                    <i class="icon-chevron-down" aria-hidden="true"></i>
                  </div>
                  <ul class="submenuItems">
                    <li><a class="dossier-patient-select" href="<?php echo $this->basePath()."/urgence/admission";?>">Dossier patient</a></li>
                    <li><a class="patient-service-select" href="<?php echo $this->basePath()."/urgence/liste-patients-admis";?>">Patient du service</a></li>
                  </ul>
                </li>
                

              </ul>

              <!-- MENU *** AFFICHAGE - TABLEAU STATISTIQUE *** infirmerie -->
              <legend class="accordion-menu" style="display:none; margin-top: 50px;">
                  <img onclick="affichagePatientsActesExamens();" style="margin-left: 15px; margin-top: 5px; margin-bottom: 5px; display: inline; cursor: pointer;" title="Actes et examens des patients" src='<?php echo $this->basePath().'/images_icons/infos.png'?>' />
                  <img onclick="imprimerRegistreDesPatientsAdmis();" style="margin-left: 10px; margin-top: 5px; margin-bottom: 5px; display: inline; cursor: pointer;" title="R&eacute;gistre &agrave; imprimer" src='<?php echo $this->basePath().'/images_icons/button_pdf.png'?>' />
                      
              </legend>

          </div>
          
          <!-- PIED DE PAGE -->
          <text style="position: fixed; top: 95%; height: 70%; left: 30px; font-size: 12px;">
            &copy; 2021 - <a href='http://www.ugb.sn' style='color: black; text-decoration: none; font-family: times new roman;' target='_blank';> PYRAMIDHIS </a>   
          </text>

        </td>

        <!-- CONTENU -->
        <td style="width: 84%; background: yello;">
          <!-- ENTETE -->
          <div id="entete-bande-style">
            
            <?php if($user['Photo']){ ?>
              <img id="icon-user-param" onclick="getMenuDeroulant();" style="box-shadow: 10 10px 20px rgba(1, 0, 0, 0.5); cursor:pointer; float: right; position:relative; right: 50px; top: 12px; width: 40px; height: 40px; border-radius: 15%; background: white;" src="<?php echo $this->basePath().'/img/photos_personnel/'.$user['Photo'].'.jpg';?>"/>
            <?php }else{ ?>
              <img id="icon-user-param"  onclick="getMenuDeroulant();" style="box-shadow: 10 10px 20px rgba(1, 0, 0, 0.5); cursor:pointer; float: right; position:relative; right: 50px; top: 12px; width: 40px; height: 40px; border-radius: 15%; background: white;" src="<?php echo $this->basePath().'/images_icons/User.png';?>"/>
            <?php } ?>

            <div style="position:relative; right: 60px; float: right; height: 20px; width: 230px; top: 13px; text-align: right; ">

              <span style="font-size: 17px; color: white; font-weight: bold; font-family: Times  New Roman;"><?php echo $prenom.' '.$nom;?></span>

              
              <div style="width: 100%; padding-top: 2px; font-size: 13px; color: white; font-weight: bold; font-family: Times  New Roman;">
              
              <?php if($user['role'] == 'medecin'){ ?>
              <a href='<?php echo $this->url('consultation');?>' style='text-decoration: none; color: white;' title='Consultation'>
                  <i class='icon-circle-arrow-right' style='font-size: 15px;'></i> &nbsp; | &nbsp; 
                </a> 
                <?php } ?>
                
                <?php //echo $service;?>
                <?php if($user['role'] == 'infirmier-service'){ ?> 
                  <span> Infirmier de service</span> 
                <?php }else if($user['role'] == 'infirmier-tri'){ ?>
                  <span> Infirmier de tri</span>
                <?php }else if($user['role'] == 'medecin'){ ?>
                  <span> M&eacute;decin</span>
                <?php } ?>
            
              </div>
            
            </div>

            

            
          </div>

          <!-- CORPS -->
          <div id="corpsContent" style="width: 100%; height: 100%; background: white;">
            <div id="corpsContentInterface">
                <?php echo $this->content; ?>
            </div>
          </div>
        
        </td>
      </tr>
      
  </table>


</body>

</html>

<style>
.ui-tooltip {
	padding: 8px;
	position: absolute;
	z-index: 9999;
	max-width: 300px;
	-webkit-box-shadow: 0 0 5px #aaa;
	box-shadow: 0 0 5px #aaa;
}

body .ui-tooltip {
	border-width: 2px;
}


 /* #bodbod { 
 	min-height: 1045px;
 	overflow-x:scroll;  
 } 

 #user-nav { 
 	min-width: 1100px;
 	 
 }   */

 /* #bodbod { overflow-y: hidden; }  */



 #corpsContent {
   overflow-y: scroll;
 }

 #corpsContentInterface {
   padding: 20px; 
   padding-top: 85px;
 }










 

</style>

<script>
var base_url = window.location.toString();
var tabUrl = base_url.split("public");

jQuery(document).ready(function($){
	setTimeout(function(){
	    $('a,img').tooltip({
	        animation: true,
	        html: true,
	        placement: 'bottom',
	        show: {
	            effect: "slideDown",
	            delay: 250
	          }
	    });
	});

});

function modifierPassword(){

  var role = "<?php echo $user['role'];?>";
  var id = 0; 
  if(role == 'medecin'){id = 1;}
  if(role == 'infirmier-tri'){id = 2;}
  if(role == 'infirmier-service'){id = 3;}

  vart=tabUrl[0]+'public/admin/modifier-password/'+id;
  $(location).attr("href",vart);
}









  $(function() {
    var Accordion = function(el, multiple) {
      this.el = el || {};
      // more then one submenu open?
      this.multiple = multiple || false;
      
      var dropdownlink = this.el.find('.dropdownlink');
      dropdownlink.on('click',
                      { el: this.el, multiple: this.multiple },
                      this.dropdown);

      dropdownlink.on('dblclick',
                      { el2: this.el2, multiple: this.multiple },
                      this.dropdown2);
    };
    
    //ANIMATION
    Accordion.prototype.dropdown = function(e) {
      var $el = e.data.el,
          $this = $(this),
          //this is the ul.submenuItems
          $next = $this.next();
      
      $next.slideToggle();
      $this.parent().toggleClass('open');
      
      if(!e.data.multiple) {
        //show only one menu at the same time
        //Afficher un seul menu à la fois
        //$el.find('.submenuItems').not($next).slideUp().parent().removeClass('open');
      }
    }

    //SANS ANIMATION
    Accordion.prototype.dropdown2 = function(e) {
      var $el2 = e.data.el2,
          $this = $(this),
          //this is the ul.submenuItems
          $next = $this.next();
      
        $next.toggle();
        $this.parent().toggleClass('open');
    }
    
    var accordion = new Accordion($('.accordion-menu'), false);
  })



function getMenuDeroulant() {
  $('#icon-user-param').w2overlay({ html: "" +
    		"" +
        "<div class='overlay-menu-deroulant' style='width: 200px; font-size: 12px;'>" +

        "<ul class=''>" +
        "<li><a onclick='modifierPassword();'><i class='icon-edit' style='font-size: 19px;'></i> Modifier infos compte</a></li>" +
        "<li><a href='<?php echo $this->url('admin', array('action'=>'logout'));?>'><i class='icon-off' style='font-size: 19px;'></i> D&eacute;connexion</a></li>" +
        "</ul>" +


        "</div>" +

        "<style> .w2ui-overlay:before{float: left; border: 1px solid rgb(28, 172, 136); top: 2px; border-bottom: 0px solid transparent; border-left:1px solid transparent;}  .w2ui-overlay{float: left; margin-left: 10px; border: 1px solid rgb(28, 172, 136); margin-top: 1 } </style>"
    		


    	
  });  
}  

</script>



<!-- 



	"<div style='border-bottom:1px solid rgb(28, 172, 136); height: 30px; background: #f9f9f9; width: 300px; text-align:center; padding-top: 10px; font-size: 13px; color: green; font-weight: bold;'>Diagnostic</div>" +
    		"<div style='height: 195px; width: 300px; padding-top:10px; text-align:center;'>" +
    		"<textarea style='height: 90%; width: 95%; max-height: 90%; max-width: 95%;' id='diagnostic_demande' > </textarea>" +
    		"</div>"


-->





























<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/urgence/affichagePatientsActesExamens.css');?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/urgence/affichagePatientsActesExamens.js'); ?>

<!-- GESTION DE L'INTERFACE D'AFFICHAGE DES PATIENTS AYANT DES ACTES ET EXAMENS COMPLEMENTAIRES -->
<!-- GESTION DE L'INTERFACE D'AFFICHAGE DES PATIENTS AYANT DES ACTES ET EXAMENS COMPLEMENTAIRES -->
<!-- GESTION DE L'INTERFACE D'AFFICHAGE DES PATIENTS AYANT DES ACTES ET EXAMENS COMPLEMENTAIRES -->

<div id="affichagePatientsActesExamensMenuGauche" title="Actes et examens compl&eacute;mentaires des patients" style="display: none;" >

  <div id="contenuListePatientTableau">
  <div style='margin-right: 40px; float:right; font-family: Times New Roman; font-size: 15px; color: green;'> 
	<i style='cursor:pointer;' id='afficherPatientAujourdhui'> Aujourd'hui </i> | 
	<i style='cursor:pointer;' id='afficherPatientHier'> Hier </i> |
	<i style='cursor:pointer;' id='afficherPatientAvantHier'> Avant hier </i> | 
	<i style='cursor:pointer;' id='afficherPatientAutresJour'> Autres .. </i>
  </div>  
  
  <table style="width: 100%;  align: center" class="table table-bordered tab_list_mini" id="actesExamensComplementairesPatients">
	<thead>
		<tr>
			<th id="numeroDossierMG_" style='width: 30px;'>
			  <input type="text" name="search_browser" value=" N&deg; dossier" class="search_init_mg" />
			</th>
			<th id="nomMG_" style='width: 15%;'>
			  <input type="text"  name="search_browser" value=" Nom" class="search_init_mg" />
			</th>
			<th id="prenomMG_" style='width: 22%;'>
			  <input type="text" name="search_browser" value=" Pr&eacute;nom" class="search_init_mg" />
			</th>
			<th id="ageMG_" style='width: 5%;'>
			  <input type="text" name="search_browser" value=" Age" class="search_init_mg" />
			</th>
			<th id="adresseMG_" style='width: 43%;'>
			  <input type="text"  name="search_browser" value=" Adresse" class="search_init_mg" />
			</th>
			<th id="optionsMG_" style='width: 5%;'>
			  <input type="hidden" class="optionsAffichage"/>Options
			</th>
		</tr>

	</thead>

	<tbody id="donnees" class="liste_patient" style="font-family: times new roman; font-size: 19px;">

            <?php /* AFFICHAGE DE LA LISTE DES PATIENTS */?>

	</tbody>

  </table>
  
  </div>
  
  <div id="contenuInfoPatientActesExamen" style="display: none;">
  
    <div style="width: 100%; height: 30px;"><span style="float: left; font-size: 25px; cursor: pointer;" onclick="retourVersListePatientsActesExamens();" title="Pr&eacute;c&eacute;dent"> &#129092; </span></div>
    <div style="width: 100%;" id="contenuInfoPatientActesExamensComplementaire" >
  
    </div>
  </div>
  
</div>

<script>
   initialisationActesExamensComplementaires();
</script>












<!-- GESTION DE L'INTERFACE DE GENERATION DE REGISTRES -->
<!-- GESTION DE L'INTERFACE DE GENERATION DE REGISTRES -->
<!-- GESTION DE L'INTERFACE DE GENERATION DE REGISTRES -->
<?php $dateDefautCalendrier = (new \DateTime ("now"))->format ( 'Y-m-d' ); ?>

<div id="generationDesRegistresDesPatientsAdmisMenuGauche" title="G&eacute;n&eacute;rer la liste des patients admis (R&eacute;gistre)" style="display: none;" >


  <div class="optionsPeriodeMG" align="center">
    <div class="optionsPeriodePathMG" align="center">
           <div class="champOP1MG"><img onclick='imprimerRegistreDesPatientsAdmisParPeriode();' src='../images_icons/Apps-Pdf-B-icon-2.png' title='imprimer'><!-- input type="date"--></div> 
           <div class="champOP2MG"><input type="date" value="<?php echo $dateDefautCalendrier; ?>"><button onclick="getRegistreDesPatientsAdmisPourPeriode();">Afficher</button></div>
    </div>    
  </div>

  
  <div class="zoneGenerationDesRegistresDesPatientsAdmis">
  
  
    <table style="width: 100%;" class="table table-bordered tab_list_mini" id="listePatientsAdmisPourLeRegistre">
	  
	  <thead style="width: 100%;">
		
		<tr style="width: 100%;">
		
			<th id="numeroDossierRegMG_" style='width: 10px;'>
			  <input type="text" name="search_browser" value=" N&deg; dossier" class="search_init_reg_mg" />
			</th>
			<th id="nomRegMG_" style='width: 10%;'>
			  <input type="text" name="search_browser" value=" Nom" class="search_init_reg_mg" />
			</th>
			<th id="prenomRegMG_" style='width: 20%;'>
			  <input type="text"  name="search_browser" value=" Pr&eacute;nom" class="search_init_reg_mg" />
			</th>
			<th id="ageRegMG_" style='width: 50px;'>
			  <input type="text"  name="search_browser" value=" Age" class="search_init_reg_mg" />
			</th>
			<th id="actesRegMG_" style='width: 20%;'>
			  <input type="text"  name="search_browser" value=" Actes" class="search_init_reg_mg" />
			</th>
			<th id="examensRegMG_" style='width: 20%;'>
			  <input type="text" name="search_browser" value=" Examens" class="search_init_reg_mg" />
			</th>
			<th id="diagnosticsRegMG_" style='width: 110px;'>
			  <input type="text" name="search_browser" value=" Diagnostics" class="search_init_reg_mg" />
			</th>
			
		</tr>

	  </thead>

	  <tbody id="donnees" class="liste_patient" style="font-family: times new roman; font-size: 19px; width: 100%;">

            <?php /* AFFICHAGE DE LA LISTE DES PATIENTS */?>

	  </tbody>

    </table>
  
  
  </div>
  
</div>


<div  style="display: none;">
<form id="imprimerRegistreDesPatientsAdmisPdf"> <button></button> </form>
</div>

<?php $dateDuJour = (new \DateTime ("now"))->format ( 'Ymd' ); ?>

<script>
  emplacementTableauVide();
  initialisationListePatientsAdmisRegistre('<?php echo $dateDuJour; ?>');
</script>
