<html>
<?php echo $this->doctype("XHTML1_TRANSITIONAL"), PHP_EOL; ?>

<meta charset="UTF-8" />
        <?php echo $this->headTitle('SIMENS '. $this->translate('Systeme Information Medical'))->setSeparator(' - ')->setAutoEscape(false) ?>

<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<?php

 echo $this->headLink()->prependStylesheet($this->basePath().'/css/bootstrap.min.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/css/jquery.contextMenu.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/css/matrix-style-cons.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/css/matrix-media.css');
 echo $this->headLink()->prependStylesheet($this->basePath().'/js/w2ui/w2ui-1.4.3.min.css');
 //echo $this->headLink()->prependStylesheet($this->basePath().'/css/menu-sidenav.css');

 $this->headScript()->appendFile($this->basePath().'/js/jquery.min.js');
 $this->headScript()->appendFile($this->basePath().'/js/matrix.js');

 echo $this->headTitle($this->pageTitle);?> 
        <?php 
             echo $this->headLink()->appendStylesheet($this->basePath().'/css/smoothness/jquery-ui.css');
             echo $this->headLink()->appendStylesheet($this->basePath().'/js/plugins/multiselect/css/multi-select.css');
        ?>

        <?php $this->headScript()->appendFile($this->basePath().'/js/jquery-1.9.1.js');
		      $this->headScript()->appendFile($this->basePath().'/js/jquery-ui.js');
		      $this->headScript()->appendFile($this->basePath().'/js/jquery.dataTables.min.js');
		      $this->headScript()->appendFile($this->basePath().'/js/plugins/contextMenu/bootstrap-contextmenu.js');
		      
		      $this->headScript()->appendFile($this->basePath().'/js/jquery.maskedinput.js');
		      $this->headScript()->appendFile($this->basePath().'/js/controle_saisie/controle_saisie.js');

		      $this->headScript()->appendFile($this->basePath().'/js/plugins/multiselect/js/jquery.multi-select.js');
		      $this->headScript()->appendFile($this->basePath().'/js/plugins/multiselect/js/jquery.quicksearch.js');
		      
		      $this->headScript()->appendFile($this->basePath().'/js/w2ui/w2ui-1.4.3.min.js');
		?>

		<?php echo $this->headScript();?>
<head>
</head>


<?php

//RECUPERER LES INFOS SUR LE MEDECIN OU SUR LE SURVEILLANT
  $user = $this->layout()->user;
  $nom = $user['Nom'];
  $prenom = $user['Prenom'];
  $service = $this->layout()->service;
  if($user['role'] == 'superAdmin') { $service = "INFORMATIQUE";}
  
  $sexe = $user['Sexe'];
  $civilite =  'Mme';
  if($sexe == 'Masculin'){$civilite = 'M';}
  
  //var_dump($user['Photo']); exit();
?>


<body id="bodbod">


  <table style="width: 100%; height: 100%; background: re;">

      <tr style="width: 100%;">
        <!-- MENU GAUCHE -->
        <td style="width: 10%; background: gree;">
          <!-- ENTETE -->
          <div style="width:100%; height: 10%;">
          </div>

          <!-- CORPS -->
          <div id="sideba" style="width:100%; height: 90%; ">
              <?php // echo $this->partial('layout/menugaucheurgence'); ?>

              <ul class="menu" >

      <li title="home"><a href="#" class="menu-button home">menu</a></li>
      
      <li title="search"><a href="#" class="search">search</a></li>
      <li title="pencil"><a href="#" class="pencil">pencil</a></li>
      <li title="about"><a href="#" class="active about">about</a></li>
      <li title="archive"><a href="#" class="archive">archive</a></li>
      <li title="contact"><a href="#" class="contact">contact</a></li>
    </ul>
    
    <ul class="menu-bar">
        <li><a href="#" class="menu-button">Menu</a></li>
        <li><a href="#">Home</a></li>
        <li><a href="#">Profile</a></li>
        <li><a href="#">Editorial</a></li>
        <li><a href="#">About</a></li>
        </ul>




          </div>
          
        </td>

        <!-- CONTENU -->
        <td style="width: 90%; background: yello;">
          <!-- ENTETE -->
          <div style="position: fixed; top:0; width: 85%; min-height: 70px; max-height: 70px; background: rgb(62, 196, 178); z-index: 100;">
            
            <!--img style="cursor:pointer; float: right; position:relative; right: 50px; top: 12px; width: 40px; height: 40px; border-radius: 15%; background: white;" src="<?php echo $this->basePath().'/images_icons/User.png';?>"/-->
          
            <user id="user">
              <section>
                <img src="https://randomuser.me/api/portraits/women/85.jpg" />
                <section>
                  <name>Sarah Dekhard</name>
                  <actions><a href="#settings">settings</a> | <a href="#logout">logout</a></actions>
                </section>
              </section>
            </user>

          </div>

          <!-- CORPS -->
          <div id="corpsContent" style="width: 100%; height: 100%; background: white;">
            <div id="corpsContentInterface">
                <?php echo $this->content; ?>
            </div>
          </div>
        
        </td>
      </tr>
      
  </table>







  
  <?php /* ?>
  <!--Header-part-->

	<div id="logoSimens" style=" height: 70px; width: 220px;">
			<div style="font-size: 28px; color: red; padding-top: 20px; padding-left: 35px;">+<div style="font-size: 27px; color: #48ce77; font-family: Bookman Old Style; float:left; ">SIMENS</div></div>
	</div>
	
  <!--div style="width: 83%; height: 50px; background-color: cyan; float: right;">
  </div-->


  

	<!--close-Header-part-->
	<!--top Menu au dessus -->
  <div id="user-nav" class="navbar navbar-inverse" style="padding-top: 0px; padding-left: 0px; width: 83%;">
  <div style="width:100%;">
    <ul class="nav" style="width:100%;">
      <li  class="dropdown" style=" width: 35%;"><a title=""  class="dropdown-toggle">
        <i> <span style="color: white; font-size: 13px;">Service: </span></i>
        <b class="caret" ></b> 
        
        <span style="font-size: 15px; color: white; font-family: Times  New Roman;"><?php echo $service;?>
          <?php if($user['role'] == 'infirmier-service'){ ?> 
            <span style="color: #68f442;"> (Infirmier de service)</span> 
          <?php }else if($user['role'] == 'infirmier-tri'){ ?>
            <span style="color: #68f442;"> (Infirmier de tri)</span>
          <?php }else if($user['role'] == 'medecin'){ ?>
            <span style="color: #68f442;"> (M&eacute;decin)</span>
          <?php } ?>
        </span></a>
        
      </li>

      <li  class="dropdown" style=" width: 48%;"><a title="" class="dropdown-toggle">
        
        <i>
        <?php if($user['Photo']){ ?>
          <img id="modifierPassword" style="cursor:pointer; position:relative; top:-2px; width: 30px; height: 30px; border-radius: 50%; background: gray;" src="<?php echo $this->basePath().'/img/photos_personnel/'.$user['Photo'].'.jpg';?>"/>
        <?php }else{ ?>
          <img id="modifierPassword" style="cursor:pointer; position:relative; top:-2px; width: 25px; height: 25px; border-radius: 50%; background: gray;" src="<?php echo $this->basePath().'/images_icons/User.png';?>"/>
        <?php } ?>
        </i>
        
        
        <span style="color: white; font-size: 13px;"><i></i> <?php echo $civilite;?>.</span>
        <b class="caret" ></b> <span style="font-size: 15px; color: white;font-family: Times  New Roman;"><?php echo $prenom.'  '.$nom;?></span></a>
      </li>

      <li style="width: 15%; ">
        <?php if($user['role'] == 'superAdmin'){ ?>
        <div style='width: 30%; padding-top: 10px; float:left;'>
          <a href="<?php echo $this->url('admin', array('action'=>'logout'));?>">
            <img src="../img/light/house.png" title="Menu d'accueil" />
          </a>
        </div>
        <?php } else if($user['role'] == 'medecin'){ ?>
        <div style='width: 30%; padding-top: 10px; float:left;'>
          <a style="padding-right: 6px;" href="<?php echo $this->url('consultation');?>">
            <img src="<?php echo $this->basePath().'/img/light/arrow_up_left.png';?>" title="Consultation" />
          </a>
        </div>
      <?php }else{ ?>
        <div style='width: 30%; padding-top: 10px; float:left;'></div>
      <?php }?>
        
        
      <div style='width: 70%; padding-top: 10px; float:left;'>
          <a href="<?php echo $this->url('admin', array('action'=>'logout'));?>">
            <img src="<?php echo $this->basePath().'/img/light/bended_arrow_right.png';?>"/> <span style="color: white; font-size: 15px; font-family: New time romans;"><i>D&eacute;connexion</i></span>
          </a>
        </div>
      </li>
    </ul>
  </div>
  </div>
  

	
	<!--Menu de droite-->
	<div id="sidebar" style="min-width: 300px;">
       <?php echo $this->partial('layout/menugaucheurgence'); ?>
    </div>
    
	<div id="content">
		<div id="content-header">
			<div style="width: 96%; margin-left: 25px;">
				<hr>
				<div class="row-fluid">
	               <?php echo $this->content; ?>
        </div>
			</div>
		</div>
	</div>
	<!--Pied de Page debut-->
	<div class="row-fluid">
		<div id="footer" class="span12" style="color: white;"><?php echo $this->partial('layout/piedpagecons'); ?> </div>
	</div>
	<!--Fin de pied de page-->

  <?php */ ?>

</body>

</html>

<style>
.ui-tooltip {
	padding: 8px;
	position: absolute;
	z-index: 9999;
	max-width: 300px;
	-webkit-box-shadow: 0 0 5px #aaa;
	box-shadow: 0 0 5px #aaa;
}

body .ui-tooltip {
	border-width: 2px;
}


 /* #bodbod { 
 	min-height: 1045px;
 	overflow-x:scroll;  
 } 

 #user-nav { 
 	min-width: 1100px;
 	 
 }   */

 #bodbod table tr:hover{ 
   background: none;
 }
 
 #corpsContent {
   overflow-y: scroll;
 }

 #corpsContentInterface {
   padding: 20px; 
   padding-top: 90px;
 }



user {
  padding: 5px;
  padding-bottom: 3px;
  flex-shrink: 0;
  position: fixed;
  font-weight: 400;
  right: 0;
  @include alpha-attribute('color', rgba($text, 0.9), white);
  z-index: 99999;

  > section {
    display: flex;
    flex-direction: row-reverse;
    align-items: center;
    > section {
      display: flex;
      flex-direction: column;
      white-space: nowrap;
    }
  }
  img {
    height: 51px;
    width: 48px;
    clip-path: circle(50% at 50% 50%);
    margin-left: 10px;
    min-height: 51px;
    min-width: 48px;
    align-items: flex-end;
  }
  name {
    font-weight: 400;
  }
  actions {
    padding: .1em 0;
    font-size: .8em;
    display: flex;
    justify-content: flex-end;
    
    a {
      padding: 0 .5em;
      color: $text;
      text-decoration: none;
      &:last-child {
        padding-right: 0;
      }
    }
  }
}


</style>

<script>
var base_url = window.location.toString();
var tabUrl = base_url.split("public");

jQuery(document).ready(function($){
	setTimeout(function(){
	    $('a,img').tooltip({
	        animation: true,
	        html: true,
	        placement: 'bottom',
	        show: {
	            effect: "slideDown",
	            delay: 250
	          }
	    });
	});

    $('#modifierPassword').click(function(){
        var role = "<?php echo $user['role'];?>";
        var id = 0; 
        if(role == 'medecin'){id = 1;}
        if(role == 'infirmier-tri'){id = 2;}
        if(role == 'infirmier-service'){id = 3;}
        
    	vart=tabUrl[0]+'public/admin/modifier-password/'+id;
        $(location).attr("href",vart);
    });
});


$(document).ready(function(){
$(".menu-button").click(function(){
$(".menu-bar").toggleClass( "open" );
})
})
</script>
